version: '2.1'

services:
  esm:
    depends_on:
      - mongo
    image: elastest/esm:latest
    container_name: esm
    hostname: esm
    environment:
      - ESM_PORT=8095
      - ESM_MONGO_HOST=mongo  # the mongo service
    expose:
      - 8095
    ports:
      - "8095:8095"
    networks:
      - elastest

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017"
    networks:
      - elastest
volumes:
  mongo-data:
    driver: local
networks:
    elastest:
      driver: bridge
