version: '2.1'

services:
  esm:
    depends_on:
      - esm-mongo
    image: elastest/esm:latest
    container_name: esm
    hostname: esm
    environment:
      - ESM_PORT=37005
      - esm-mongo_HOST=esm-mongo  # the mongo service
      - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19999/
      - ET_EDM_MYSQL_HOST=edm-mysql
      - ET_EDM_MYSQL_PORT=3306
      - ET_EDM_ELASTICSEARCH_API=http://edm-elasticsearch:9200/
      - ET_EDM_API=http://edm:37003/
      - ET_EPM_API=http://epm:37002/
      - ET_ETM_API=http://etm:37006/
      - ET_ESM_API=http://esm:37005/
    expose:
      - 37005
    ports:
      - "37005:37005"
    networks:
      - elastest

  esm-mongo:
    image: mongo
    container_name: mongo
    hostname: esm-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017"
    networks:
      - elastest
volumes:
  mongo-data:
    driver: local
networks:
    elastest:
      driver: bridge
