version: '2'

services:
  esm:
    depends_on:
      - mongo
    image: elastest/esm:latest
    container_name: esm
    hostname: esm
    environment:
      - ESM_PORT=8080
      - MONGO_HOST=mongo  # the mongo service
      - SENTINEL_KAFKA_EP=kafka.demonstrator.info:9092
      - SENTINEL_TOPIC=user-1-cyclops
      - SENTINEL_SERIES_NAME=app-logs
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017"
volumes:
  mongo-data:
    driver: local
